import { Metadata } from "next";
import Navbar from "./Components/Navbar/page";
import "./style.css"
export const metadata : Metadata = {
  title: {
    default:"Next.js tutorials",
    template:"%s | Codeevolotion",
    absolute:""
  },
  description : "Generated by Next.js"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <div>
          <Navbar></Navbar>
          {children}
        </div>
      </body>
    </html>
  );
}
