
export const  metadata = {
  title:"Product data",
   description : "Generated by Next.js"
}
export default function ProductDetilsLayout({children}:{children:React.ReactNode}){
    return <>
     <nav >This My Product Navbar</nav>
      {children}
      <footer>This My Product footer</footer>
    </>
}